apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-hello-app
  template:
    metadata:
      labels:
        app: my-hello-app
    spec:
      containers:
      - name: my-hello-app-container
        image: my-hello-app
        imagePullPolicy: Never